// Code generated by go.anx.io/go-anxcloud/tools object-generator - DO NOT EDIT!

package v1

import (
	"context"
)

// GetIdentifier returns the primary identifier of a Resource object
func (o Resource) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}

// GetIdentifier returns the primary identifier of a ResourceWithTag object
func (o ResourceWithTag) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}
