// Code generated by go.anx.io/go-anxcloud/tools object-generator - DO NOT EDIT!

package v1_test

import (
	. "github.com/onsi/ginkgo/v2"
	testutils "go.anx.io/go-anxcloud/pkg/utils/test"

	"go.anx.io/go-anxcloud/pkg/api/types"
	apipkg "go.anx.io/go-anxcloud/pkg/apis/core/v1"
)

var _ = Describe("Object Location", func() {
	o := apipkg.Location{}

	ifaces := make([]interface{}, 0, 1)
	{
		var i types.Object
		ifaces = append(ifaces, &i)
	}

	testutils.ObjectTests(&o, ifaces...)
})

var _ = Describe("Object Resource", func() {
	o := apipkg.Resource{}

	ifaces := make([]interface{}, 0, 2)
	{
		var i types.Object
		ifaces = append(ifaces, &i)
	}
	{
		var i types.ResponseDecodeHook
		ifaces = append(ifaces, &i)
	}

	testutils.ObjectTests(&o, ifaces...)
})

var _ = Describe("Object ResourceWithTag", func() {
	o := apipkg.ResourceWithTag{}

	ifaces := make([]interface{}, 0, 4)
	{
		var i types.Object
		ifaces = append(ifaces, &i)
	}
	{
		var i types.ResponseFilterHook
		ifaces = append(ifaces, &i)
	}
	{
		var i types.RequestBodyHook
		ifaces = append(ifaces, &i)
	}
	{
		var i types.FilterRequestURLHook
		ifaces = append(ifaces, &i)
	}

	testutils.ObjectTests(&o, ifaces...)
})
