version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
    - LittleFox94
    - marioreggiori
    - eiabea
  - package-ecosystem: "gomod"
    directory: "/tools/"
    schedule:
      interval: "daily"
    assignees:
    - LittleFox94
    - marioreggiori
    - eiabea
