// Code generated by go.anx.io/go-anxcloud/tools object-generator - DO NOT EDIT!

package v1

import (
	"context"
)

// GetIdentifier returns the primary identifier of a Template object
func (o *Template) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}
