// Code generated by go.anx.io/go-anxcloud/tools object-generator - DO NOT EDIT!

package v1_test

import (
	. "github.com/onsi/ginkgo/v2"
	testutils "go.anx.io/go-anxcloud/pkg/utils/test"

	"go.anx.io/go-anxcloud/pkg/api/types"
	apipkg "go.anx.io/go-anxcloud/pkg/apis/vsphere/v1"
)

var _ = Describe("Object IPs", func() {
	o := apipkg.IPs{}

	ifaces := make([]interface{}, 0, 1)
	{
		var i types.Object
		ifaces = append(ifaces, &i)
	}

	testutils.ObjectTests(&o, ifaces...)
})

var _ = Describe("Object ProvisionProgress", func() {
	o := apipkg.ProvisionProgress{}

	ifaces := make([]interface{}, 0, 1)
	{
		var i types.Object
		ifaces = append(ifaces, &i)
	}

	testutils.ObjectTests(&o, ifaces...)
})

var _ = Describe("Object Template", func() {
	o := apipkg.Template{}

	ifaces := make([]interface{}, 0, 4)
	{
		var i types.Object
		ifaces = append(ifaces, &i)
	}
	{
		var i types.PaginationSupportHook
		ifaces = append(ifaces, &i)
	}
	{
		var i types.FilterRequestURLHook
		ifaces = append(ifaces, &i)
	}
	{
		var i types.ResponseDecodeHook
		ifaces = append(ifaces, &i)
	}

	testutils.ObjectTests(&o, ifaces...)
})

var _ = Describe("Object VirtualMachine", func() {
	o := apipkg.VirtualMachine{}

	ifaces := make([]interface{}, 0, 4)
	{
		var i types.Object
		ifaces = append(ifaces, &i)
	}
	{
		var i types.RequestBodyHook
		ifaces = append(ifaces, &i)
	}
	{
		var i types.FilterRequestURLHook
		ifaces = append(ifaces, &i)
	}
	{
		var i types.ResponseDecodeHook
		ifaces = append(ifaces, &i)
	}

	testutils.ObjectTests(&o, ifaces...)
})
