// Code generated by go.anx.io/go-anxcloud/tools object-generator - DO NOT EDIT!

package v1

import (
	"context"
)

// GetIdentifier returns the primary identifier of a Application object
func (o Application) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}

// GetIdentifier returns the primary identifier of a Function object
func (o Function) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}
