// Code generated by go.anx.io/go-anxcloud/tools object-generator - DO NOT EDIT!

package v1_test

import (
	. "github.com/onsi/ginkgo/v2"
	testutils "go.anx.io/go-anxcloud/pkg/utils/test"

	"go.anx.io/go-anxcloud/pkg/api/types"
	apipkg "go.anx.io/go-anxcloud/pkg/apis/e5e/v1"
)

var _ = Describe("Object Application", func() {
	o := apipkg.Application{}

	ifaces := make([]interface{}, 0, 1)
	{
		var i types.Object
		ifaces = append(ifaces, &i)
	}

	testutils.ObjectTests(&o, ifaces...)
})

var _ = Describe("Object Function", func() {
	o := apipkg.Function{}

	ifaces := make([]interface{}, 0, 1)
	{
		var i types.Object
		ifaces = append(ifaces, &i)
	}

	testutils.ObjectTests(&o, ifaces...)
})
