// Code generated by go.anx.io/go-anxcloud/tools object-generator - DO NOT EDIT!

package v2

import (
	"context"
)

// GetIdentifier returns the primary identifier of a Bucket object
func (o *Bucket) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}

// GetIdentifier returns the primary identifier of a Endpoint object
func (o *Endpoint) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}

// GetIdentifier returns the primary identifier of a Key object
func (o *Key) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}

// GetIdentifier returns the primary identifier of a Region object
func (o *Region) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}

// GetIdentifier returns the primary identifier of a S3Backend object
func (o *S3Backend) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}

// GetIdentifier returns the primary identifier of a Tenant object
func (o *Tenant) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}

// GetIdentifier returns the primary identifier of a User object
func (o *User) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}
