// Code generated by go.anx.io/go-anxcloud/tools object-generator - DO NOT EDIT!

package v1

import (
	"context"
)

// GetIdentifier returns the primary identifier of a Address object
func (o *Address) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}

// GetIdentifier returns the primary identifier of a Prefix object
func (o *Prefix) GetIdentifier(ctx context.Context) (string, error) {
	return o.Identifier, nil
}
