# If someone with write access comments "/ok-to-test" on a pull request, emit a repository_dispatch event
name: Ok to test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          named-args: true
          permission: write
          dispatch-type: workflow
          commands: ok-to-test
          static-args: |
            pr_id=${{ github.event.issue.number }}
            ref=refs/pull/${{ github.event.issue.number }}/merge

